### ISSUE TITLE
Some issue?

### ISSUE THREAD

**Issue by MysteriousKnight** [Cytranics/LordGPT#31]
================================================================================
Exception Timestamp: 2023-04-30 15:12:23.774381
Traceback (most recent call last):
  File "LordGPT.py", line 1243, in <module>
  File "LordGPT.py", line 1229, in main_loop
  File "LordGPT.py", line 1173, in openai_bot_handler
  File "LordGPT.py", line 1115, in command_handler
  File "LordGPT.py", line 968, in search_engine
KeyError: 'organic_results'

**Comment by MysteriousKnight** [comment]
Fixed:
Basically i had an old .json settings file for lordgpt - 
Deleted it - started LordGPT.exe again - put in my API Key - 
Now it works.
