### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by JackONeill199** [Cytranics/LordGPT#9]
Goal: Create a list of all units from the game "Beyond all Reason". The information can be found on this website "www.beyondallreason.info/armada" also search subdomains. Save the information from the page to a file. Analyze the strengths and weaknesses of the units and save a report as a PDF.
Creating detailed plan to achive the goal....
LordGPT Thoughts: Task list generated
Currently :       1. Research the game 'Beyond all Reason' and its units.
Next Task:        2. Scrape the website 'www.beyondallreason.info/armada' and its subdomains for unit information.
Executing CMD:    create_task_list
CMD Argument:     1. Research the game 'Beyond all Reason' and its units.
2. Scrape the website 'www.beyondallreason.info/armada' and its subdomains for unit information.
3. Save the scraped information to a file.
4. Analyze the strengths and weaknesses of each unit.
5. Create a PDF report of the unit analysis.
6. Save the PDF report.
7. Verify the accuracy of the PDF report.
8. Mission accomplished: Submit the PDF report.

Enter the amount of responses you want to process automatically (Default 1): 2
LordGPT Thoughts: Downloading website content...
Currently :       2. Scrape the website 'www.beyondallreason.info/armada' and its subdomains for unit information.
Next Task:        3. Save the scraped information to a file.
Executing CMD:    download_file
CMD Argument:     https://www.beyondallreason.info/armada

Traceback (most recent call last):
  File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1355, in <module>
    main_loop()
  File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1345, in main_loop
    bot_send = openai_bot_handler(bot_prompt, loop, "assistant")
  File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1296, in openai_bot_handler
    handler_response = command_handler(
  File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1230, in command_handler
    return function(
  File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 953, in download_file
    process = subprocess.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by Cytranics** [comment]
Are you using the script or windows version?

From: JackONeill199 ***@***.***>
Sent: Wednesday, April 26, 2023 5:04 PM
To: Cytranics/LordGPT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cytranics/LordGPT] File not found (Issue #9)


Goal: Create a list of all units from the game "Beyond all Reason". The information can be found on this website "www.beyondallreason.info/armada<http://www.beyondallreason.info/armada>" also search subdomains. Save the information from the page to a file. Analyze the strengths and weaknesses of the units and save a report as a PDF.
Creating detailed plan to achive the goal....
LordGPT Thoughts: Task list generated
Currently : 1. Research the game 'Beyond all Reason' and its units.
Next Task: 2. Scrape the website 'www.beyondallreason.info/armada' and its subdomains for unit information.
Executing CMD: create_task_list
CMD Argument: 1. Research the game 'Beyond all Reason' and its units.
2. Scrape the website 'www.beyondallreason.info/armada' and its subdomains for unit information.
3. Save the scraped information to a file.
4. Analyze the strengths and weaknesses of each unit.
5. Create a PDF report of the unit analysis.
6. Save the PDF report.
7. Verify the accuracy of the PDF report.
8. Mission accomplished: Submit the PDF report.

Enter the amount of responses you want to process automatically (Default 1): 2
LordGPT Thoughts: Downloading website content...
Currently : 2. Scrape the website 'www.beyondallreason.info/armada' and its subdomains for unit information.
Next Task: 3. Save the scraped information to a file.
Executing CMD: download_file
CMD Argument: https://www.beyondallreason.info/armada

Traceback (most recent call last):
File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1355, in
main_loop()
File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1345, in main_loop
bot_send = openai_bot_handler(bot_prompt, loop, "assistant")
File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1296, in openai_bot_handler
handler_response = command_handler(
File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 1230, in command_handler
return function(
File "E:\github\Lord-GPT github\LordGPT\LordGPT.py", line 953, in download_file
process = subprocess.run(
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
with Popen(*popenargs, **kwargs) as process:
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by JackONeill199** [comment]
I cloned the Github repo and executed the script LordGPT.py via CMD.

**Comment by JackONeill199** [comment]
I just pulled the "Windows Version" update and am testing with it.

**Comment by Cytranics** [comment]
I just pused a fix to use CURL instead of wget to support both windows and linux.

**Comment by Cytranics** [comment]
Fixed in latest version
